egovernments/DIVOC

.gitignore, registry/Common.json, registry/Facility.json, registry/Operator.json, registry/Signature.json, vaccination_api/common/common.go, vaccination_api/config/config.json, vaccination_api/controller/controller.go, vaccination_api/controller/controller_test.go, vaccination_api/go.mod, vaccination_api/main.go, vaccination_api/models/configuration.go, vaccination_api/models/token.go
Tested creating operator with postgre sql backend.
=> Adding schema for registry to use with opensaber (tested syntax)

portal/src/components/FacilityActivation/FacilityActivation.js, portal/src/components/FacilityAdjustingRate/FacilityAdjustingRate.js
=> Changed Status to 'Active' by default, conditional rendering of districts

vaccination_api/pkg/certify_handler.go
02-Jan-2006 and 2020-12-02 are the templates support for recipientDOB while uploading certificate csv
=> 02-Jan-2006 template support to recipientDOB while uploading certificate csv

certificate_processor/config/config.js, certificate_processor/main.js, certificate_processor/notification.js, certificate_processor/package.json
SMTP configs are just placeholders now
=> Notification module added to handle sms/email

vaccination_api/pkg/db/db.go, vaccination_api/pkg/handler.go
* populating CertifyUploadErrors table, when uploaded certificate csv has any data errors
* added GET /certify/uploads/{id}/errors API which returns the error rows for given uploaded certificate csv
=> added json tag to CertifyUploadFields

backend/certificate_signer/signer.js, backend/vaccination_api/pkg/handler.go
- Fetching mobile number from _contact_ array. e.g:["tel:123456789"], using regex and setting it in cert.
- Query on that number to fetch cert.
=> Setting mobile on certificate and querying by mobile for certificate

mobile/src/Dashboard/Dashboard.js, mobile/src/components/Help/index.js, mobile/src/components/RecipientQueueTable/index.js, mobile/src/jsonSchema/walk_in_form.json
Placeholder Help component added
=> Facility app bug fixes

portal/src/components/FacilitiesRegistry/FacilitiesRegistry.js, portal/src/components/PreEnrollment/PreEnrollment.js, portal/src/components/UploadHistory/UploadHistory.js, portal/src/components/UploadHistoryTable/index.js, portal/src/components/VaccinatorsRegistry/VaccinatorsRegistry.js, portal/src/utils/constants.js
Now we show success in upload history column, and also the total count of success csv upload for selected type in the tab.
=> UI Changes on csv upload history

backend/vaccination_api/pkg/certify_handler.go, interfaces/vaccination-api.yaml
marked required fields
* making a field required changed the type of field in go code to its respective pointer. Changes in `certify_handler.go` take care of these
=> certify api validations

portal/src/components/facility/SearchVaccinatorResults/SearchVaccinatorResults.module.css, portal/src/components/facility/SearchVaccinatorResults/SearchVaccinatorResultsView.js, portal/src/components/facility/VaccinatorDetails/VaccinatorDetails.js, portal/src/components/facility/VaccinatorList/VaccinatorList.css, portal/src/components/facility/VaccinatorList/VaccinatorList.js, portal/src/components/facility/Vaccinators/Vaccinators.js
* activate/inactivate vaccinator from the facility admin portal
* search existing vaccinator and add them to a facility
=> Vaccinator Details page edits in facility admin portal

backend/vaccination_api/pkg/handler.go, backend/vaccination_api/pkg/utils.go, backend/vaccination_api/swagger_gen/models/certification_request.go, backend/vaccination_api/swagger_gen/restapi/operations/certification/certify_responses.go, interfaces/vaccination-api.yaml
* At least one of DOB/Age should be present
* If Age is not given, it will be calculated from DOB
=> DOB Age validations

backend/vaccination_api/config/application-default.yml, backend/vaccination_api/config/config.go, backend/vaccination_api/pkg/certify_handler.go, backend/vaccination_api/pkg/db/db.go, backend/vaccination_api/pkg/handler.go, backend/vaccination_api/pkg/utils.go
* Added recipientAge and recipientAddress headers to the bulk certify csv
* at least one of recipientAge and recipientDOB should be present in Headers and Fields (non-empty)
* If Age is not given, it will be calculated from DOB
* Other required validations
=> Bulk certify validations

portal/src/components/FacilityActivation/FacilityActivation.js, portal/src/components/FacilityAdjustingRate/FacilityAdjustingRate.js, portal/src/components/FacilityController/FacilityController.js, portal/src/components/FacilityDetails/FacilityDetails.js, portal/src/components/FacilityFilterTab/index.js
* multiselect districts
* make inactive/active message
=> multiselect districts, make active/inactive message

mobile/src/AppDatabase.js, mobile/src/Home/Home.js, mobile/src/Services/ApiServices.js, mobile/src/SyncFacade.js, mobile/src/components/BatchCodeForm/index.js, mobile/src/utils/date_utils.js
We are sending vaccination details with number of dosage and effective Until date with certify error handling.
=> Fix Certify dosage

portal/src/components/facility/Vaccinators/Vaccinators.js
fix for : after activating or inactivating vaccinators, status change is not reflected automatically (tab change/refresh required)
=> vaccinators inactive/active

portal/src/components/FacilityActivation/FacilityActivation.js, portal/src/components/FacilityController/FacilityController.js
* multi select district fix -> replaceAll (string to array)
* reset districts when changing tabs
* missing space in jsx
=> Testing fixes

backend/vaccination_api/pkg/handler.go, backend/vaccination_api/pkg/programs.go
- added checks to query programs only if any programs are associated
- added functionality to handle multiple facilities with the same code
=> fixed get current active programs for facility

backend/portal_api/swagger_gen/models/vaccinator.go, backend/portal_api/swagger_gen/models/vaccinator_update_request.go, backend/portal_api/swagger_gen/restapi/embedded_spec.go, backend/vaccination_api/swagger_gen/models/vaccinator.go, backend/vaccination_api/swagger_gen/restapi/embedded_spec.go, interfaces/admin-portal.yaml, portal/src/components/facility/VaccinatorDetails/VaccinatorDetails.js
added certified field as mandatory for program in vaccinator
added osid field as mandatory for update vaccinator details API
making program active by default when added to a vaccinator
=> Fix: add program for vaccinator failing

.github/workflows/ci.yml, .gitignore, Makefile, docker-compose.e2e.yml, docker-compose.yml, e2e/Dockerfile, e2e/e2e_test.py, e2e/e2e_test_spy.sh, e2e/requirements.txt, e2e/test_data/certify.json, e2e/test_data/get_certificate.json, e2e/test_utils.py, keycloak/e2e-divoc-realm.json
* POST certify
* check registry
=> /certify test

backend/portal_api/pkg/facility_user_handler.go, backend/portal_api/swagger_gen/models/facility_user.go, interfaces/admin-portal.yaml, portal/src/components/FacilityForm/FacilityForm.js
issue: opensaber erasing the nested field in programs array (schedule) when updating admins array
fix: sending programs array as part of update request
=> edit admin fix

portal/src/components/ProgramRegistration/ProgramRegistration.js
Not related to appointment & registration
=> only active vaccines allowed while program registration

backend/portal_api/pkg/handler.go, backend/portal_api/pkg/services/facility_service.go, backend/portal_api/swagger_gen/restapi/operations/notify_facilities.go, backend/portal_api/swagger_gen/restapi/operations/notify_facilities_parameters.go, interfaces/admin-portal.yaml, portal/src/components/FacilityDetails/FacilityDetails.js, portal/src/components/NotifiyPopup/NotifiyPopup.js, portal/src/components/NotifiyPopup/NotifyPopup.module.css
* Controller has to give a message to notify.
* No longer using pendingTasks template
=> Facility Controller | Notify

backend/registration_api/pkg/handler.go, backend/registration_api/pkg/models/FacilitySchedule.go, backend/registration_api/pkg/services/appointment_service.go, backend/registration_api/pkg/services/redis_service.go, backend/registration_api/swagger_gen/restapi/embedded_spec.go, backend/registration_api/swagger_gen/restapi/operations/get_slots_for_facilities_parameters.go, backend/registration_api/swagger_gen/restapi/operations/get_slots_for_facilities_urlbuilder.go, interfaces/registration-api.yaml
* getFacilitySlots | use `zrangebyscore` to fetch latest
* initFacilitySlots | set expiry for slot key & clean-up old slot keys  in set
* key_ttl = appointmentStartTime - currentTime
* slot key cleanup -> `zremrangebyscore` (-inf to currentTime)
=> slot clean up

public_app/src/App.css, public_app/src/components/Registration/AddMember/FormPersonalDetails.js, public_app/src/components/Registration/AddMember/error-constants.js, public_app/src/components/Registration/AddMember/index.css, public_app/src/components/Registration/AddMember/index.js, public_app/src/components/Registration/Members/index.js, public_app/src/utils/validations.js
adding max validation and allowing spaces for name field
=> input label and style changes

backend/certificate_signer/main.js, backend/certificate_signer/signer.js, backend/vaccination_api/cmd/analytics_feed/main.go, backend/vaccination_api/cmd/digilocker_support_api/as_external_api.go, backend/vaccination_api/cmd/digilocker_support_api/digilocker_api.go, backend/vaccination_api/cmd/digilocker_support_api/main.go, backend/vaccination_api/config/application-default.yml, backend/vaccination_api/config/config.go, backend/vaccination_api/pkg/models/Certificate.go, backend/vaccination_api/pkg/models/CertifiedMessage.go
- updated analytics feed to listen to certified topic
- reverted certify topic analytics …
- created consumer to record events on certified topic
- added sort by created at while fetching certificates
=> analytics and fetch latest certificate changes

backend/certificate_signer/signer.js, registry/VaccinationCertificate.json
- everted postalCode default value 
-  added dose value in VaccinationCertificate schema
=> reverted postalCode default value and added dose value

backend/registration_api/config/config.go, backend/registration_api/pkg/models/FacilitySchedule.go, public_app/src/components/Appointment/index.js
using a default offset to correctly infer slot startTime. 
Helps in correctly fetching slots
=> Avoiding past slots

backend/portal_api/config/config.go, backend/portal_api/pkg/base_csv_upload.go, backend/portal_api/pkg/db/db.go, backend/portal_api/pkg/facility_csv_upload_handler.go, backend/portal_api/pkg/get_csv_handler.go, backend/portal_api/pkg/handler.go, backend/portal_api/pkg/pre_enrollment_csv_upload_handler.go, backend/portal_api/pkg/services/enrollmentack_consumer.go, backend/portal_api/pkg/services/kafka_service.go, backend/portal_api/pkg/vaccinator_csv_upload.go, backend/registration_api/config/config.go, backend/registration_api/pkg/consumers/create_enrollment_consumer.go, backend/registration_api/pkg/services/kafka_service.go, portal/src/components/UploadHistory/UploadHistory.js
publishEnrollment messages for system-admin upload instead of directly writing to registry
=> enrollment upload -> publishEnrollment

backend/registration_api/pkg/handler.go, backend/registration_api/pkg/utils/utils.go, public_app/src/components/Appointment/index.css, public_app/src/components/Appointment/index.js, public_app/src/utils/CustomDate.js
* getSlots -> return slots starting from tomorrow
* appointment confirmation dialog changes
* leftover appointment slots after failed search
* appointment slots -> sort according to time
=> Booking issues [DIV-42]

portal/src/components/VaccineRegistrationForm/index.js
* -ve integer check for time and money
=> time & money validations

interfaces/facilities.csv, portal/src/components/UploadHistory/UploadHistory.js, portal/src/utils/constants.js
* sorting the uploadHistory response in UI with respect to createdTime
* pointing the download csv template to main branch
* removing serialNum column from  the facility csv template
=> Upload History changes in admin portal

keycloak-mobile-number-login-spi/themes/certificate-login/login/mobile-login.ftl, keycloak-mobile-number-login-spi/themes/certificate-login/login/verify-otp.ftl, keycloak-mobile-number-login-spi/themes/facility-admin/login/mobile-login.ftl, keycloak-mobile-number-login-spi/themes/facility-admin/login/verify-otp.ftl, keycloak-mobile-number-login-spi/themes/facility-operator/login/mobile-login.ftl, keycloak-mobile-number-login-spi/themes/facility-operator/login/verify-otp.ftl, keycloak-mobile-number-login-spi/themes/sys-admin/login/mobile-login.ftl, keycloak-mobile-number-login-spi/themes/sys-admin/login/verify-otp.ftl, mobile/src/App.js, mobile/src/App.scss, mobile/src/AppDatabase.js, mobile/src/Home/Home.js, mobile/src/Home/Home.scss, mobile/src/Services/ApplicationConfigsDB.js, mobile/src/components/RegisterBeneficiaryForm/error-constants.js, mobile/src/components/RegisterBeneficiaryForm/index.js, mobile/src/components/VerifyMobile/index.js, mobile/src/components/WalkEnrollments/context.js, mobile/src/redux/reducers/flagrConfig.js, mobile/src/styles/colors.scss
- fixed redirecting to httpss
- fixed scrolling to top in walkin form
- updated to skip otp form for offline scenario
- fixed passing identity in proper field
- added nationality to walkin form
=> DIV-79 Fixed walkin form issues

backend/registration_api/pkg/consumers/create_enrollment_consumer.go, backend/registration_api/pkg/services/enrollment_service.go, backend/registration_api/pkg/services/kafka_service.go, backend/vaccination_api/pkg/enrollment.go, backend/vaccination_api/pkg/handler.go, backend/vaccination_api/pkg/services/enrollmentack_consumer.go
VaccinationAPI
* Added dose, facilityCode, certified, appointmentDate [vaccinationDate] in Enrolment Message for Walk-In
* Changed VaccinationDetails to CertificationRequest from []byte
RegistrationAPI
* For walk-in, override enrollmentCode in vaccinationDetails in payload with the generated one or the found duplicate
=> walk-in enrolment duplication handling

backend/portal_api/pkg/pre_enrollment_csv_upload_handler.go, backend/registration_api/pkg/consumers/create_enrollment_consumer.go, backend/registration_api/pkg/handler.go, backend/registration_api/pkg/services/appointment_service.go, backend/registration_api/pkg/services/enrollment_service.go, interfaces/enrollments.csv
* if facilityCode is given in csv, appointment will be auto booked
* if facilityCode does not have slots, enrollment will be created but appointment won't be booked & error show in admin portal
* if a csv contains duplicate enrollment, appointment will be created if not booked previously
* if program is not activated for facility or slots not configured and initiated, Error shown will be `no slots available`
* failed csv uploads can be retried after slot initiation ( if error is `no slots available`)
=> facilityCode to PreEnrollment CSV

backend/certificate_signer/signer.js, backend/vaccination_api/Makefile, backend/vaccination_api/cmd/digilocker_support_api/main.go, backend/vaccination_api/cmd/digilocker_support_api/main_test.go, backend/vaccination_api/cmd/divoc-certification-ack/main.go, backend/vaccination_api/cmd/divoc-certification-ack/main_test.go, backend/vaccination_api/pkg/handler_test.go
fixes: https://github.com/egovernments/DIVOC/issues/762
=> Cleaning up credential subject identity handle

backend/certificate_api/main.js, backend/certificate_api/src/routes/certificate_controller.js, docker-compose.yml, public_app/public/locales/en/translation.json, public_app/src/components/CertificateStatus/index.js, public_app/src/components/CertificateView/CertificateView.js
Capability to download EU Certificate in pdf format and Fhir certificate in json file
=> Feat: download EU certificate and Fhir certificate

backend/certificate_api/main.js, backend/certificate_api/src/routes/certificate_controller.js, public_app/public/locales/en/translation.json, public_app/src/components/Registration/Members/index.js
QRCode download feature added in public portal.
=> QRCode download for citizen

backend/certificate_api/configs/templates/certificate_template.html, backend/certificate_api/src/routes/certificate_controller.js, backend/certificate_api/src/services/certificate_service.js, infra/vars/main.yml, public_app/src/config.js
Please refer https://digit-discuss.atlassian.net/browse/DIV-7850 for more details
=> Introduce Vaccination Events table in certificate PDF instead of just the particular dose vaccination info in generic implementation

backend/vaccination_api/cmd/digilocker_support_api/main.go, backend/vaccination_api/pkg/models/Certificate.go, backend/vaccination_api/pkg/models/Certificate_test.go
DIV-8057: Changes in India template to accommodate booster dose information
https://digit-discuss.atlassian.net/browse/DIV-8057
=> Updated Template changes  for booster dose in India

verification/src/components/CertificateStatus/index.js, verification/src/constants.js
https://digit-discuss.atlassian.net/browse/DIV-8058
=> Changes in verification page for booster dose India

backend/vaccination_api/cmd/digilocker_support_api/main.go, verification/src/components/CertificateStatus/index.js, verification/src/constants.js
Changes made both in domestic and international certificates for booster dose in India as per the latest approved cert. template
Related tickets:
https://digit-discuss.atlassian.net/browse/DIV-8057
https://digit-discuss.atlassian.net/browse/DIV-8058
https://digit-discuss.atlassian.net/browse/DIV-8059
=> Changes in India Booster dose templates

backend/vaccination_api/pkg/handler.go, backend/vaccination_api/pkg/services/kafka_service.go, public_app/public/locales/en/translation.json, public_app/src/components/CertificateStatus/index.js
=> Revoke certificate changes DIV-8077

docker-compose.yml, registry/Dockerfile, registry/RevokedCertificate.json
Reverts egovernments/DIVOC#865
For error info refer https://github.com/egovernments/DIVOC/runs/4800812459
=> Revert "updating registry base image to latest sunbird registry" as it breaks Docker Image CI Build 

backend/vaccination_api/cmd/reconciliation/main.go, backend/vaccination_api/cmd/reconciliation/main_test.go
=> Request date updating while checking data consistency

backend/certificate_api/configs/config.js, backend/certificate_api/src/routes/certificate_controller.js, backend/certificate_signer/config/config.js, backend/certificate_signer/signer.js, backend/certificate_signer/tests/signer.test.js, docker-compose.yml
=> DID and Passport changes DIV-8151

backend/vaccination_api/cmd/reconciliation/main_test.go
=> updating unit tests

backend/certificate_signer/config/constants.js, backend/vaccination_api/cmd/digilocker_support_api/main.go, backend/vaccination_api/pkg/models/Certificate.go
=> Added Covovax to Vaccine List DIV-8063

backend/certificate_signer/config/config.js, backend/certificate_signer/main.js, docker-compose.yml
=> Country code fix DIV-8177

interfaces/certificate-api.yaml
=> DIV-8213 | adding qrcode type and updating producers for certificate-api swagger file

backend/vaccination_api/cmd/certificate_processor/main.go, backend/vaccination_api/pkg/services/kafka_service.go, backend/vaccination_api/pkg/services/redis_service.go, docker-compose.yml
=> DIV-8269 | Revocation API - bug fixes

backend/certificate_api/src/services/configuration_service.js, backend/certificate_api/tests/configuration_service.test.js, default-configuration/etcd/updateConfigs.sh
=> Using etcdClient and Allowed schemes[data] in configuration_service

default-configuration/etcd/README.md
=> ReadMe for etcd DIV-8328

backend/certificate_api/configs/constants.js, backend/certificate_api/src/routes/eu_certificate_controller.js, backend/certificate_api/src/services/configuration_service.js, backend/certificate_api/tests/configuration_service.test.js, default-configuration/etcd/euVaccineCertificateTemplate.html, default-configuration/etcd/updateConfigs.sh
=> DIV-8354 | Add EU certificate as a separate template from DDCC template

backend/certificate_api/src/services/certificate_service.js
=> Add certificateId and nationality ot certificate_api 8368

backend/certificate_api/src/services/certificate_service.js
=> Added additional vaccine details and certificate raw to controller DIV-8374

Makefile
=> Creating a release branch

public_app/src/components/CertificateStatus/index.js, public_app/src/config.js
=> verifier in sync with signer DIV-8411

portal/src/components/CustomButton/index.css, portal/src/components/CustomButton/index.js, portal/src/components/CustomDateWidget/index.css, portal/src/components/CustomTextWidget/index.css, portal/src/components/CustomTextWidget/index.js, portal/src/components/PrintCertificate/PrintCertificate.js, portal/src/components/PrintCertificate/PrintCertificate.module.css, portal/src/components/facility/Vaccinators/Vaccinators.js, portal/src/utils/constants.js
@egov-joy @samarthgr please review
=> DIV-8321 | Print facility staff should retrieve beneficiaries by phon…e and dob and can print certificates

backend/vaccination_api/cmd/digilocker_support_api/as_external_api.go, backend/vaccination_api/cmd/digilocker_support_api/main.go, public_app/src/components/CertificateView/CertificateView.js
=> removed revoked certificates in public app DIV-8428

backend/registration_api/pkg/services/kafka_service.go, backend/vaccination_api/cmd/analytics_feed/main.go, backend/vaccination_api/pkg/services/enrollmentack_consumer.go
=> async error handling in Vaccination-api DIV-8282

nginx/nginx.conf
=> DIV-8492 | Update digilocker endpoint pointing in nginx.conf

nginx/nginx.conf
=> Reverted digilocker Url from /cert to /cert/api

backend/certificate_api/main.js, backend/certificate_api/src/routes/certificate_controller.js, backend/certificate_api/src/routes/eu_certificate_controller.js, backend/certificate_api/src/services/registry_service.js
=> extracting out entity type

e2e/requirements.txt
=> e2e test failure build fix

backend/certificate_signer_library/main.js
=> DIV-8463 | signCertificateWithoutPersisting function call update with correct name

backend/kernel_library/services/app_configuration_service.go, default-configuration/etcd/COUNTRY_SPECIFIC_FEATURES.json
@egov-joy @samarthgr please review
=> fixing empty unmarshalling of country specific features

docker-compose.yml
=> registry_perRequest_indexCreation_enabled set to false

docker-compose.yml
=> registry_perRequest_indexCreation_enabled set to false 2.0.0

docker-compose.yml
=> registry_perRequest_indexCreation_enabled set to false 2.1.0

backend/certificate_api/src/services/certificate_service.js
=> implemented philippines production fixes in certificate api

docker-compose.yml, imports/realm-export.json
=> changes to realm-export to run both Sunbird and Divoc

backend/vc-certification-service/certification-service-swagger.yml, backend/vc-certification-service/main.js, backend/vc-certification-service/package-lock.json, backend/vc-certification-service/package.json, backend/vc-management-service/main.js, backend/vc-management-service/management-service-swagger.yml, backend/vc-management-service/package-lock.json, backend/vc-management-service/package.json
adding swagger api docs in vc-certification and vc-management services
@egov-joy @srprasanna @varadeth Please review
=> DIV-8653 | adding swagger api docs

backend/vc-management-service/src/controllers/issuer.controller.js, backend/vc-management-service/src/utils/utils.js
=> DIV-8654 | issuer userid validation

backend/vc-certification-service/certification-service-swagger.yml, backend/vc-management-service/management-service-swagger.yml, backend/vc-management-service/src/configs/config.js, backend/vc-management-service/src/configs/constants.js, backend/vc-management-service/src/controllers/schema.controller.js, backend/vc-management-service/src/routes/schema.routes.js, backend/vc-management-service/src/services/sunbird.service.js
@prasanna-egov @varadeth @egov-joy
=> HLM-312 | adding update schema end points

backend/vaccination_api/cmd/analytics_feed/main.go
@prasanna-egov @varadeth Please review.
=> HLM-472 | Create a clickhouse table for handling API Logs

backend/vc-certification-service/src/middleware/auth.middleware.js, backend/vc-management-service/src/middleware/auth.middleware.js
@egov-joy @prasanna-egov 
403 for empty token already exists
=> HLM-305 | made status 401 for invalid token

backend/vc-certification-service/src/configs/constants.js, backend/vc-certification-service/src/controllers/certificate.controller.js
@prasanna-egov @egov-joy please review
=> HLM-481 | Generate QR Code

backend/notification-service/config/application-default.yml, backend/notification-service/config/config.go, backend/notification-service/pkg/consumers/configure_consumers.go, backend/notification-service/pkg/consumers/notify_consumer.go, backend/notification-service/pkg/models/NotificationPayload.go, backend/notification-service/pkg/services/construct_message.go
@prasanna-egov  @saiprakash-v @varadeth
=> HLM - 325 | Create new consumer in notificaion-service to accept raw messages

registry/RevokedVC.json
=> HLM-501 | Adding revoked vc schema

backend/vaccination_api/pkg/models/Certificate.go
@prasanna-egov @egov-joy @varadeth
=> HLM-535 | Date Parsing  

backend/Makefile
=> HLM-311 | Added registry-async-handler in backend make

backend/vc-certification-service/package-lock.json, backend/vc-certification-service/package.json, backend/vc-certification-service/src/controllers/certificate.controller.js, backend/vc-certification-service/src/routes/certificate.route.js
=> HLM-554 | Add Required fields validator

backend/vc-certification-service/src/controllers/certificate.controller.js, backend/vc-certification-service/src/services/sunbird.service.js
=> HLM-555 | Remove body from axios delete call for soft delete sunbird-rc api call

backend/vc-management-service/main.js, backend/vc-management-service/management-service-swagger.yml, backend/vc-management-service/package.json, backend/vc-management-service/src/configs/config.js, backend/vc-management-service/src/configs/constants.js, backend/vc-management-service/src/controllers/schema.controller.js, backend/vc-management-service/src/controllers/template.controller.js, backend/vc-management-service/src/controllers/tenant.controller.js, backend/vc-management-service/src/routes/template.routes.js, backend/vc-management-service/src/routes/tenant.routes.js, backend/vc-management-service/src/services/keycloak.service.js, backend/vc-management-service/src/services/sunbird.service.js, backend/vc-management-service/src/utils/utils.js, keycloak/src-realm-export.json, vc-registry/Tenant.json
@prasanna-egov @varadeth Please review
I have refactored all occurences of issuer to tenant, also added capability to create and assign a new role, everytime a new tenant is added (based on username)
Also Updated realm-export file after Increasing timeout of keycloak token and changing admin-api role access to create new roles etc.
=> HLM-509 | Creation of tenant

.github/workflows/ci.yml
=> HLM-564 | Run pipeline on commit or pull request to vc-issuance-platform

backend/certificate_signer/config/constants.js, backend/vaccination_api/cmd/digilocker_support_api/main.go
@prasanna-egov please review and merge
=> adding new vaccines for certificate issuance to foreign nationals

backend/vc-certification-service/package.json, backend/vc-certification-service/src/controllers/certificate.controller.js, backend/vc-certification-service/src/services/sunbird.service.js, backend/vc-certification-service/src/services/validation.service.js, backend/vc-certification-service/tests/certificate.controller.test.js
@srprasanna @varadeth Please review.
=> HLM-540 | Add validations to certification endpoint

backend/vc-certify-consumer/main.js
@prasanna-egov @varadeth @saiprakash-v
=> HLM-541 | Produce post_vc_certify for failed certificates

backend/vc-certification-service/src/middleware/auth.middleware.js, backend/vc-certify-consumer/main.js, backend/vc-management-service/src/middleware/auth.middleware.js
@prasanna-egov @varadeth  @saiprakash-v
=> HLM-575 | remove manage, certification roles and code refactoring in vc-certify-consumer

backend/vc-certify-consumer/main.js, backend/vc-certify-consumer/src/configs/constants.js, backend/vc-certify-consumer/src/services/sunbird.service.js, vc-registry/TransactionCertificateMap.json
Consuming from post vc certify and creating transaction certificate ID mapping in a new transaction table
@prasanna-egov @varadeth please review
=> HLM-553 | Adding new consumer for post-vc-certify

backend/vc-certification-service/src/controllers/certificate.controller.js
=> HLM-576 | Revoke certificate using certificateId instead of osid

backend/vc-management-service/src/controllers/tenant.controller.js
@prasanna-egov @saiprakash-v please review
=> HLM-603 | create role in smallcase only

backend/vc-certification-service/src/controllers/certificate.controller.js, backend/vc-certification-service/src/services/sunbird.service.js, backend/vc-certification-service/src/utils/certification.utils.js, backend/vc-certification-service/tests/certificate.controller.test.js
@prasanna-egov @varadeth Please review
=> HLM-602 | updating get certificate flow with certificateID

backend/vc-management-service/Dockerfile, backend/vc-management-service/management-service-swagger.yml, backend/vc-management-service/package-lock.json, backend/vc-management-service/package.json, backend/vc-management-service/src/configs/constants.js, backend/vc-management-service/src/controllers/context.controller.js, backend/vc-management-service/src/controllers/schema.controller.js, backend/vc-management-service/src/routes/context.routes.js, backend/vc-management-service/src/services/keycloak.service.js, backend/vc-management-service/src/services/redis.service.js, backend/vc-management-service/src/services/sunbird.service.js, backend/vc-management-service/tests/context.controller.test.js, backend/vc-management-service/tests/redis.service.test.js, backend/vc-management-service/tests/sunbird.service.test.js, docker-compose-vc-issuance.yml
@saiprakash-v @prasanna-egov @ajay-beehyv please review
=> HLM-581 | Get context api

backend/vc-certify-consumer/Dockerfile, backend/vc-certify-consumer/jest.config.js, backend/vc-certify-consumer/package.json, backend/vc-certify-consumer/testEnvVars.js, backend/vc-certify-consumer/tests/sunbird.service.test.js, backend/vc-certify-consumer/tests/vc.certification.service.test.js
@prasanna-egov @saiprakash-v @varadeth
=> HLM-632 |  Added tests to vc-certify-consumer

backend/vc-management-service/src/controllers/schema.controller.js, backend/vc-management-service/src/models/error.js
@prasanna-egov @varadeth please review
=> HLM-585 | validation to ensure schema name to be same as evidence type

backend/vc-certification-service/src/models/errors.js, backend/vc-certification-service/src/services/validation.service.js, docker-compose-vc-issuance.yml
@prasanna-egov @varadeth please review
=> HLM-647 | changed validations for mandatory fields

backend/vc-certification-service/src/controllers/certificate.controller.js, backend/vc-certification-service/src/routes/certificate.route.js, backend/vc-certification-service/tests/certificate.controller.test.js
@prasanna-egov @saiprakash-v @varadeth
=> HLM-650 | remove delete endpoint and controller

backend/vc-certification-service/src/configs/constants.js, docker-compose-vc-issuance.yml
Correct the schedule to run on a daily basis instead of every minute. Earlier, missed correcting the schedule after testing
@saiprakash-v @varadeth
=> HLM-573 | scheduler fix

backend/vc-certification-service/src/services/validation.service.js
@prasanna-egov @varadeth please review
=> HLM-647 | checks for validFrom and validTill null values

backend/vc-certification-service/src/controllers/certificate.controller.js, backend/vc-certification-service/src/services/validation.service.js
@prasanna-egov @saiprakash-v @varadeth
=> HLM-653 | Validate Revoke end date

keycloak/src-realm-export.json
=> Keycloak token validity increase

backend/vc-management-service/src/configs/config.js, backend/vc-management-service/src/configs/constants.js, backend/vc-management-service/src/controllers/context.controller.js, backend/vc-management-service/src/routes/context.routes.js, backend/vc-management-service/tests/context.controller.test.js, docker-compose-vc-issuance.yml
=> Fix context

backend/vc-certify-consumer/main.js, backend/vc-certify-consumer/package.json, backend/vc-certify-consumer/src/configs/config.js, backend/vc-certify-consumer/src/services/keycloak.service.js, backend/vc-certify-consumer/src/services/redis.service.js, backend/vc-certify-consumer/src/services/sunbird.service.js, backend/vc-certify-consumer/src/services/webhook.service.js, docker-compose-vc-issuance.yml, vc-registry/Tenant.json
=> Adding webhook integration

backend/vc-management-service/src/configs/config.js, backend/vc-management-service/src/routes/context.routes.js, docker-compose-vc-issuance.yml
=> Minio s3 fix

backend/vc-management-service/src/controllers/schema.controller.js
=> updating get evidence type logic, if evidence is an array

backend/vc-management-service/src/controllers/context.controller.js
=> changing constants to config

backend/vc-management-service/src/controllers/schema.controller.js
=> HLM-731 | Pass Additional fields while creating schema

backend/vc-certification-service/src/controllers/certificate.controller.js, backend/vc-certification-service/src/services/sunbird.service.js
=> HLM-638 | Added startDate and endDate to verifyCertificate response

docker-compose-vc-issuance.yml, imports/config.json
@srprasanna @saiprakash-v Please review.
=> Upgrade sunbird-rc to the latest version to support multiple signature

keycloak-mobile-number-login-spi/themes/vc-issuance/login/login-reset-password.ftl, keycloak-mobile-number-login-spi/themes/vc-issuance/login/messages/messages_en.properties, keycloak/src-realm-export.json
=> HLM-675 | keycloak Forgot password

backend/certificate_api/src/services/certificate_service.js
=> HLM-957 | Added patch to remove spaces in EU

backend/certificate_api/src/services/certificate_service.js, backend/certificate_signer/main.js, default-configuration/etcd/VACCINE_ICD.json
=> 2.1.3-generic

backend/certificate_signer/config/constants.js, backend/vaccination_api/cmd/digilocker_support_api/main.go, backend/vaccination_api/pkg/models/Certificate.go
=> HLM-964 | Added gemcovac vaccine

Tenant-Portal-Dockerfile, VC-Dockerfile, docker-compose-vc-issuance.yml, nginx/tenant-nginx.conf, nginx/vc-nginx.conf
=> decoupling tenant-portal from gateway

Tenant-Portal-Dockerfile, nginx/tenant-nginx.conf, nginx/vc-nginx.conf, tenant-portal/src/App.js, tenant-portal/src/i18n.js, tenant-portal/src/index.js, tenant-portal/src/utils/keycloak.js
=> HLM-1036 | translations bug fixes

keycloak-mobile-number-login-spi/Makefile, keycloak-mobile-number-login-spi/themes/vc-issuance/login/error.ftl, keycloak-mobile-number-login-spi/themes/vc-issuance/login/info.ftl, keycloak-mobile-number-login-spi/themes/vc-issuance/login/login-reset-password.ftl, keycloak-mobile-number-login-spi/themes/vc-issuance/login/login-update-password.ftl, keycloak-mobile-number-login-spi/themes/vc-issuance/login/login-verify-email.ftl, keycloak-mobile-number-login-spi/themes/vc-issuance/login/login.ftl, keycloak-mobile-number-login-spi/themes/vc-issuance/login/messages/messages_en.properties, keycloak-mobile-number-login-spi/themes/vc-issuance/login/resources/css/login.css, tenant-portal/src/App.js, tenant-portal/src/components/Header/Header.js
=> HLM-1063 | Forget password info.ftl fixes

backend/vc-certification-service/src/controllers/certificate.controller.js, backend/vc-certification-service/src/models/errors.js, backend/vc-certification-service/src/services/validation.service.js, backend/vc-certification-service/src/utils/certification.utils.js, backend/vc-management-service/src/controllers/context.controller.js, backend/vc-management-service/src/controllers/schema.controller.js, backend/vc-management-service/src/controllers/template.controller.js, backend/vc-management-service/src/controllers/tenant.controller.js, backend/vc-management-service/src/controllers/transaction.controller.js, backend/vc-management-service/src/models/error.js
=> Extending Custom error class from NodeJS Error

keycloak-mobile-number-login-spi/themes/vc-issuance/login/login-update-password.ftl, tenant-portal/src/components/Header/Header.js
=> change password screen

keycloak/src-realm-export.json, nginx/vc-nginx.conf, tenant-portal/Dockerfile, tenant-portal/nginx/nginx.conf, tenant-portal/src/components/BreadcrumbComponent/BreadcrumbComponent.js, tenant-portal/src/components/GenerateToken/GenerateToken.js, tenant-portal/src/components/Header/Header.js, tenant-portal/src/components/Home/Home.js, tenant-portal/src/config.json, tenant-portal/src/i18n.js, tenant-portal/src/utils/keycloak.js
=> HLM-1164 | Making tenant portal available on baseURL

keycloak-mobile-number-login-spi/themes/vc-issuance/login/login-update-password.ftl
=> HLM-1137 | fix back button in update password

tenant-portal/src/components/CreateSchema/CreateSchema.js, tenant-portal/src/components/CreateSchema/CreateSchema.module.css
=> HLM-1099 | create schema page UI fixes

backend/vc-management-service/src/controllers/schema.controller.js, backend/vc-management-service/src/middleware/role-add.middleware.js, tenant-portal/package.json, tenant-portal/public/locales/en/translation.json, tenant-portal/public/locales/hi/translation.json, tenant-portal/src/components/JsonUpload/JsonUpload.js, tenant-portal/src/components/ManageSchemaHome/ManageSchemaHome.js, tenant-portal/src/components/SchemaAttributes/SchemaAttributes.js, tenant-portal/src/components/TestAndPublish/TestAndPublish.js
=> json flow bug fixes

tenant-portal/public/locales/en/translation.json, tenant-portal/public/locales/hi/translation.json, tenant-portal/src/components/ManageSchemaHome/ManageSchemaHome.js, tenant-portal/src/components/ManageTempModal/ManageTempModal.js, tenant-portal/src/components/SchemaAttributes/SchemaAttributes.js, tenant-portal/src/components/UploadTemplate/UploadTemplate.js
=> UI-bug-fixes(Manage Upload Temp)

tenant-portal/src/components/SchemaAttributes/SchemaAttributes.js, tenant-portal/src/components/TestAndPublish/TestAndPublish.js, tenant-portal/src/utils/customUtils.js, tenant-portal/src/utils/schema.js
=> multi-templates select

verification/src/constants.js
=> Set Timezone as IST

verification-app/Dockerfile, verification-app/src/config.js, verification-app/src/utils/CustomDate.js
=> HLM-1517 | Add Timezone to formatDate

tenant-portal/src/components/ManageSchemaHome/ManageSchemaHome.js, tenant-portal/src/components/ManageTempModal/ManageTempModal.js, tenant-portal/src/components/SchemaAttributes/SchemaAttributes.js
=> HLM-1618 | Manage schema loading and handle manage template close

docker-compose-vc-issuance.yml
=> Updating docker compose
